GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/61fd2b4ac350875b9ffb38bb

###
DELETE http://localhost:3001/api/persons/61fd2df91f5648c5ddd693f0

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "ja",
    "number": "1234"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Boob",
    "number": "1234"
}

###
PUT  http://localhost:3001/api/persons/61fa6b25dbced80ae0e30de6
content-type: application/json

{
    "name": "Marilyn Moonroe",
    "number": "515-715-3697"
}
